language: csharp

mono: none

#dotnet: 2.2.104
#  - 3.0.100-preview3-010431
#  - 2.2.104
#  - 2.2.103
#  - 2.2.102
addons:
  snaps:
    - name: dotnet-sdk
      classic: true
      channel: latest/beta

matrix:
  allow_failures:
    - os: osx

solution: Starter.Net

#stages:
#  - init
#  - deploy

jobs:
  include:
    - stage: "Init"
      name: "Install on Linux"
#      dotnet: 2.2.104
      os: linux
      script: dotnet restore
    - stage: "Init"
      os: windows
      dotnet: 2.2.104
      name: "install on windows"
      script: dotnet restore
    - stage: "Init"
      os: osx
      dotnet: 2.2.104
      name: "install on osx"
      script: dotnet restore

    - stage: "Verify"
      os: linux
      dotnet: 2.2.104
      name: "build on linux"
      script: dotnet build
    - stage: "Verify"
      os: windows
      dotnet: 2.2.104
      name: "build on windows"
      script: dotnet build
    - stage: "Verify"
      os: osx
      dotnet: 2.2.104
      name: "build on osx"
      script: dotnet build
    - stage: "Verify"
      os: linux
      dotnet: 2.2.104
      name: "Test on Linux"
      script: dotnet test
    - stage: "Verify"
      os: windows
      dotnet: 2.2.104
      name: "Test on Windows"
      script: dotnet test
    - stage: "Verify"
      os: osx
      dotnet: 2.2.104
      name: "Test on osx"
      script: dotnet test
#
#    - stage: weird_stage
#      name: "placeholder stage"
#      dotnet: 2.2.104
#      script: echo "deploy done"
#      os: osx
